#!/bin/sh
MASTER=${1:-"master"}
WORKING_BRANCH=`git branch -l | grep "*" | cut -d " " -f 2`
git rebase $MASTER || exit 1

if [ -z "$(git log master..HEAD  --pretty=oneline | grep '\[from now\]')" ]
then
    git checkout $MASTER && git reset --hard $WORKING_BRANCH && git branch -D $WORKING_BRANCH
else
    echo "Current branch has now commit.\nPlease fixup it by 'git now --fixup'"
    exit 1
fi
